// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for hub documents */
interface HubDocumentData {
    /**
     * title field in *hub*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hub.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * description field in *hub*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hub.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * publication date field in *hub*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: hub.publication_date
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    publication_date: prismicT.DateField;
    /**
     * hero image field in *hub*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hub.hero_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    hero_image: prismicT.ImageField<never>;
    /**
     * Slice Zone field in *hub*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: hub.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HubDocumentDataSlicesSlice>;
}
/**
 * Slice for *hub → Slice Zone*
 *
 */
type HubDocumentDataSlicesSlice = ParagraphSlice | TableSlice;
/**
 * hub document from Prismic
 *
 * - **API ID**: `hub`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HubDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<HubDocumentData>, "hub", Lang>;
/** Content for job position documents */
interface JobPositionDocumentData {
    /**
     * Slice Zone field in *job position*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: job_position.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<JobPositionDocumentDataSlicesSlice>;
}
/**
 * Slice for *job position → Slice Zone*
 *
 */
type JobPositionDocumentDataSlicesSlice = JobPositionSlice;
/**
 * job position document from Prismic
 *
 * - **API ID**: `job_position`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type JobPositionDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<JobPositionDocumentData>, "job_position", Lang>;
/** Content for legal policy documents */
interface LegalPolicyDocumentData {
    /**
     * Slice Zone field in *legal policy*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: legal_policy.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<LegalPolicyDocumentDataSlicesSlice>;
}
/**
 * Slice for *legal policy → Slice Zone*
 *
 */
type LegalPolicyDocumentDataSlicesSlice = ParagraphSlice;
/**
 * legal policy document from Prismic
 *
 * - **API ID**: `legal_policy`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LegalPolicyDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<LegalPolicyDocumentData>, "legal_policy", Lang>;
/** Content for news documents */
interface NewsDocumentData {
    /**
     * title field in *news*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: news.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * description field in *news*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: news.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * publication date field in *news*
     *
     * - **Field Type**: Timestamp
     * - **Placeholder**: *None*
     * - **API ID Path**: news.publication_date
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/timestamp
     *
     */
    publication_date: prismicT.TimestampField;
    /**
     * hero image field in *news*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: news.hero_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    hero_image: prismicT.ImageField<never>;
    /**
     * Slice Zone field in *news*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: news.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<NewsDocumentDataSlicesSlice>;
}
/**
 * Slice for *news → Slice Zone*
 *
 */
type NewsDocumentDataSlicesSlice = ParagraphSlice;
/**
 * news document from Prismic
 *
 * - **API ID**: `news`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<NewsDocumentData>, "news", Lang>;
export type AllDocumentTypes = HubDocument | JobPositionDocument | LegalPolicyDocument | NewsDocument;
/**
 * Primary content in JobPosition → Primary
 *
 */
interface JobPositionSliceDefaultPrimary {
    /**
     * PositionName field in *JobPosition → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: job_position.primary.positionname
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    positionname: prismicT.TitleField;
    /**
     * detail link field in *JobPosition → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: job_position.primary.detail_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    detail_link: prismicT.LinkField;
    /**
     * Description field in *JobPosition → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: job_position.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Image field in *JobPosition → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: job_position.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Default variation for JobPosition Slice
 *
 * - **API ID**: `default`
 * - **Description**: `JobPosition`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type JobPositionSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<JobPositionSliceDefaultPrimary>, never>;
/**
 * Slice variation for *JobPosition*
 *
 */
type JobPositionSliceVariation = JobPositionSliceDefault;
/**
 * JobPosition Shared Slice
 *
 * - **API ID**: `job_position`
 * - **Description**: `JobPosition`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type JobPositionSlice = prismicT.SharedSlice<"job_position", JobPositionSliceVariation>;
/**
 * Item in Paragraph → Items
 *
 */
export interface ParagraphSliceDefaultItem {
    /**
     * content field in *Paragraph → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: paragraph.items[].content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
}
/**
 * Default variation for Paragraph Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Paragraph`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ParagraphSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<ParagraphSliceDefaultItem>>;
/**
 * Item in Paragraph → Items
 *
 */
export interface ParagraphSliceInterviewItem {
    /**
     * content field in *Paragraph → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: paragraph.items[].content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
    /**
     * title field in *Paragraph → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: paragraph.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
}
/**
 * Interview variation for Paragraph Slice
 *
 * - **API ID**: `interview`
 * - **Description**: `Paragraph`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ParagraphSliceInterview = prismicT.SharedSliceVariation<"interview", Record<string, never>, Simplify<ParagraphSliceInterviewItem>>;
/**
 * Slice variation for *Paragraph*
 *
 */
type ParagraphSliceVariation = ParagraphSliceDefault | ParagraphSliceInterview;
/**
 * Paragraph Shared Slice
 *
 * - **API ID**: `paragraph`
 * - **Description**: `Paragraph`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ParagraphSlice = prismicT.SharedSlice<"paragraph", ParagraphSliceVariation>;
/**
 * Primary content in Table → Primary
 *
 */
interface TableSliceDefaultPrimary {
    /**
     * title field in *Table → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: table.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * description field in *Table → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: table.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Item in Table → Items
 *
 */
export interface TableSliceDefaultItem {
    /**
     * table header field in *Table → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: table.items[].table_header
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    table_header: prismicT.KeyTextField;
    /**
     * table data field in *Table → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: table.items[].table_data
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    table_data: prismicT.RichTextField;
}
/**
 * Default variation for Table Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Table`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TableSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TableSliceDefaultPrimary>, Simplify<TableSliceDefaultItem>>;
/**
 * Slice variation for *Table*
 *
 */
type TableSliceVariation = TableSliceDefault;
/**
 * Table Shared Slice
 *
 * - **API ID**: `table`
 * - **Description**: `Table`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TableSlice = prismicT.SharedSlice<"table", TableSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { HubDocumentData, HubDocumentDataSlicesSlice, HubDocument, JobPositionDocumentData, JobPositionDocumentDataSlicesSlice, JobPositionDocument, LegalPolicyDocumentData, LegalPolicyDocumentDataSlicesSlice, LegalPolicyDocument, NewsDocumentData, NewsDocumentDataSlicesSlice, NewsDocument, AllDocumentTypes, JobPositionSliceDefaultPrimary, JobPositionSliceDefault, JobPositionSliceVariation, JobPositionSlice, ParagraphSliceDefaultItem, ParagraphSliceDefault, ParagraphSliceInterviewItem, ParagraphSliceInterview, ParagraphSliceVariation, ParagraphSlice, TableSliceDefaultPrimary, TableSliceDefaultItem, TableSliceDefault, TableSliceVariation, TableSlice };
    }
}
