// Code generated by Slice Machine. DO NOT EDIT.

import Paragraph from './Paragraph'
import Table from './Table'

export { Paragraph, Table }

export const components = {
  paragraph: Paragraph,
  table: Table,
}
