// Code generated by Slice Machine. DO NOT EDIT.

import JobPosition from './JobPosition'
import Paragraph from './Paragraph'
import Table from './Table'

export { JobPosition, Paragraph, Table }

export const components = {
  job_position: JobPosition,
  paragraph: Paragraph,
  table: Table,
}
