name: AWS S3 Sync

on:
  push:
    branches:
      - master_for_aws#

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - run: aws s3 sync ./docs s3://anti-pattern.co.jp/ --delete --exact-timestamps
      - run: aws cloudfront create-invalidation --distribution-id E23DFD6PG2IV7X --paths "/*"
